version: '3'
services:
  ghost:
    image: ghost:5-alpine
    ports:
      - 2368:2368
    volumes:
      - .:/var/lib/ghost/content/themes/casper
    environment:
      url: http://localhost:2368
      NODE_ENV: development

  node:
    image: node:12-alpine
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/var/lib/fantasma
    working_dir: /var/lib/fantasma
    tty: true
